apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-api-mysql
  labels:
    app: fast-api-mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fast-api-mysql
  template:
    metadata:
      labels:
        app: fast-api-mqsql
    spec:
      containers:
      - name: fast-api-mysql
        image: fast-api-mysql
        env:
        - name: db_user
          value: root
        - name: db_password
          value: admin
        - name: db_name
          value: flask_test
        - name: db_host
          value: 34.125.218.1
        ports:
        - containerPort: 8080

