name: docker-build-push
  on:
    push:
    branches: [main]
with:
  image: jency92/fast-api-mysql
  registry: docker.pkg.github.com
  username: ${{ github.actor }}
  password: ${{ secrets.GITHUB_TOKEN }}

